spring.application.name=SATSA

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.hntwarufvocghlgfcgux
spring.datasource.username=postgres.hntwarufvocghlgfcgux
spring.datasource.password=satsaadmin1806

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
application.security.jwt.secret-key=McvbIkvPaVjhmKBwFdHDZxvFEAzgaJ8XJrc6BsVnKP19VUwAW7gZFMy62HhSI
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

#Credenciales de RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.missing-queues-fatal: false